parameters:
#    mapas_estadisticos.example.class: SistemaEncuesta\MapasEstadisticosBundle\Example

services:
#    mapas_estadisticos.example:
#        class: %mapas_estadisticos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
