<?php

namespace Proxies\__CG__\SistemaEncuesta\EncuestasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Encuesta extends \SistemaEncuesta\EncuestasBundle\Entity\Encuesta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'id', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'nombreEncuesta', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'descripcion', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'tipoEncuesta', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'fechaInicio', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'fechaFin', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'definitiva', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'encuestaFase2', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'preguntas', 'contactados', 'contactadosSufragio', 'candidatos', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'incidencia', 'contactadoComando');
        }

        return array('__isInitialized__', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'id', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'nombreEncuesta', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'descripcion', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'tipoEncuesta', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'fechaInicio', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'fechaFin', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'definitiva', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'encuestaFase2', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'preguntas', 'contactados', 'contactadosSufragio', 'candidatos', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Encuesta' . "\0" . 'incidencia', 'contactadoComando');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Encuesta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreEncuesta($nombreEncuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreEncuesta', array($nombreEncuesta));

        return parent::setNombreEncuesta($nombreEncuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEncuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEncuesta', array());

        return parent::getNombreEncuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEncuesta($tipoEncuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEncuesta', array($tipoEncuesta));

        return parent::setTipoEncuesta($tipoEncuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEncuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEncuesta', array());

        return parent::getTipoEncuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFin($fechaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFin', array($fechaFin));

        return parent::setFechaFin($fechaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFin', array());

        return parent::getFechaFin();
    }

    /**
     * {@inheritDoc}
     */
    public function getPreguntas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreguntas', array());

        return parent::getPreguntas();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefinitiva($definitiva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefinitiva', array($definitiva));

        return parent::setDefinitiva($definitiva);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefinitiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefinitiva', array());

        return parent::getDefinitiva();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncuestaFase2($encuestaFase2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncuestaFase2', array($encuestaFase2));

        return parent::setEncuestaFase2($encuestaFase2);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncuestaFase2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncuestaFase2', array());

        return parent::getEncuestaFase2();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactados(\SistemaEncuesta\EncuestasBundle\Entity\Contactados $contactados = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactados', array($contactados));

        return parent::setContactados($contactados);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactados', array());

        return parent::getContactados();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactadosSufragio(\SistemaEncuesta\EncuestasBundle\Entity\ContactadosSufragio $contactadosSufragio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactadosSufragio', array($contactadosSufragio));

        return parent::setContactadosSufragio($contactadosSufragio);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactadosSufragio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactadosSufragio', array());

        return parent::getContactadosSufragio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCandidatos(\SistemaEncuesta\EncuestasBundle\Entity\Candidatos $candidatos = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCandidatos', array($candidatos));

        return parent::setCandidatos($candidatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidatos', array());

        return parent::getCandidatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactadoComando(\SistemaEncuesta\EncuestasBundle\Entity\ContactadoComando $contactadoComando = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactadoComando', array($contactadoComando));

        return parent::setContactadoComando($contactadoComando);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactadoComando()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactadoComando', array());

        return parent::getContactadoComando();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosSi($repuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosSi', array($repuesta));

        return parent::totalContactadosSi($repuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosSiPregunta($repuesta, $numPregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosSiPregunta', array($repuesta, $numPregunta));

        return parent::totalContactadosSiPregunta($repuesta, $numPregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosSufragioSi($repuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosSufragioSi', array($repuesta));

        return parent::totalContactadosSufragioSi($repuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosSufragioSiPregunta($repuesta, $numPregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosSufragioSiPregunta', array($repuesta, $numPregunta));

        return parent::totalContactadosSufragioSiPregunta($repuesta, $numPregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadoComandoSi($repuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadoComandoSi', array($repuesta));

        return parent::totalContactadoComandoSi($repuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadoComandoSiPregunta($repuesta, $numPregunta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadoComandoSiPregunta', array($repuesta, $numPregunta));

        return parent::totalContactadoComandoSiPregunta($repuesta, $numPregunta);
    }

    /**
     * {@inheritDoc}
     */
    public function setIncidencia(\SistemaEncuesta\EncuestasBundle\Entity\Incidencias $incidencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncidencia', array($incidencias));

        return parent::setIncidencia($incidencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncidencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncidencia', array());

        return parent::getIncidencia();
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosSufragio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosSufragio', array());

        return parent::totalContactadosSufragio();
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactados($mun, $resp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactados', array($mun, $resp));

        return parent::totalContactados($mun, $resp);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosParroquia($paq, $resp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosParroquia', array($paq, $resp));

        return parent::totalContactadosParroquia($paq, $resp);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadosCircuito($circuito, $resp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadosCircuito', array($circuito, $resp));

        return parent::totalContactadosCircuito($circuito, $resp);
    }

    /**
     * {@inheritDoc}
     */
    public function totalContactadoComando($mun, $resp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'totalContactadoComando', array($mun, $resp));

        return parent::totalContactadoComando($mun, $resp);
    }

}
