<?php

namespace Proxies\__CG__\SistemaEncuesta\EncuestasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ComandoCamp extends \SistemaEncuesta\EncuestasBundle\Entity\ComandoCamp implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'id', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'area', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'identificador', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'cedula', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'apellidosNombres', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'telefono1', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'correo', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'cargoComando');
        }

        return array('__isInitialized__', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'id', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'area', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'identificador', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'cedula', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'apellidosNombres', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'telefono1', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'correo', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\ComandoCamp' . "\0" . 'cargoComando');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ComandoCamp $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArea($area)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArea', array($area));

        return parent::setArea($area);
    }

    /**
     * {@inheritDoc}
     */
    public function getArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArea', array());

        return parent::getArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentificador($identificador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificador', array($identificador));

        return parent::setIdentificador($identificador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificador', array());

        return parent::getIdentificador();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidosNombres($apellidosNombres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidosNombres', array($apellidosNombres));

        return parent::setApellidosNombres($apellidosNombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidosNombres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidosNombres', array());

        return parent::getApellidosNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono1($telefono1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono1', array($telefono1));

        return parent::setTelefono1($telefono1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono1', array());

        return parent::getTelefono1();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', array($correo));

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', array());

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargoComando(\SistemaEncuesta\EncuestasBundle\Entity\CargoComando $cargoComando = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargoComando', array($cargoComando));

        return parent::setCargoComando($cargoComando);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargoComando()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargoComando', array());

        return parent::getCargoComando();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
