<?php

namespace Proxies\__CG__\SistemaEncuesta\EncuestasBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidatos extends \SistemaEncuesta\EncuestasBundle\Entity\Candidatos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'id', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'apellidoNombre', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'partido', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'cantidadVotosTotal', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'cantidadVotosTotalLista', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'tipoEleccion', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'identificador', 'rutaFoto', 'foto', 'encuesta', 'cvCandidatos');
        }

        return array('__isInitialized__', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'id', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'apellidoNombre', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'partido', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'cantidadVotosTotal', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'cantidadVotosTotalLista', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'tipoEleccion', '' . "\0" . 'SistemaEncuesta\\EncuestasBundle\\Entity\\Candidatos' . "\0" . 'identificador', 'rutaFoto', 'foto', 'encuesta', 'cvCandidatos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidatos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoNombre($apellidoNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoNombre', array($apellidoNombre));

        return parent::setApellidoNombre($apellidoNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoNombre', array());

        return parent::getApellidoNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartido($partido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartido', array($partido));

        return parent::setPartido($partido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartido', array());

        return parent::getPartido();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadVotosTotal($cantidadVotosTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadVotosTotal', array($cantidadVotosTotal));

        return parent::setCantidadVotosTotal($cantidadVotosTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadVotosTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadVotosTotal', array());

        return parent::getCantidadVotosTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadVotosTotalLista($cantidadVotosTotalLista)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadVotosTotalLista', array($cantidadVotosTotalLista));

        return parent::setCantidadVotosTotalLista($cantidadVotosTotalLista);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadVotosTotalLista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadVotosTotalLista', array());

        return parent::getCantidadVotosTotalLista();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEleccion($tipoEleccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEleccion', array($tipoEleccion));

        return parent::setTipoEleccion($tipoEleccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEleccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEleccion', array());

        return parent::getTipoEleccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaFoto($rutaFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaFoto', array($rutaFoto));

        return parent::setRutaFoto($rutaFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaFoto', array());

        return parent::getRutaFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentificador($identificador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificador', array($identificador));

        return parent::setIdentificador($identificador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificador', array());

        return parent::getIdentificador();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto(\Symfony\Component\HttpFoundation\File\UploadedFile $foto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function subirFoto($directorioDestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'subirFoto', array($directorioDestino));

        return parent::subirFoto($directorioDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function setEncuesta(\SistemaEncuesta\EncuestasBundle\Entity\Encuesta $encuestas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncuesta', array($encuestas));

        return parent::setEncuesta($encuestas);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncuesta', array());

        return parent::getEncuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvCandidatos(\SistemaEncuesta\EncuestasBundle\Entity\CvCandidatos $cvCandidatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvCandidatos', array($cvCandidatos));

        return parent::setCvCandidatos($cvCandidatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvCandidatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvCandidatos', array());

        return parent::getCvCandidatos();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
