parameters:
#    usuario.example.class: SistemaEncuesta\UsuarioBundle\Example

services:
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#    login_listener:
#    class: SistemaEncuesta\UsuarioBundle\Listener\LoginListener
#    arguments: [@router]
    #synthetic:true
#    tags:
#        - { name: kernel.event_listener, event: security.interactive_login }
#        - { name: kernel.event_listener, event: kernel.response }
